### PR TITLE
akka-cluster-sharding context propagation

### PR DESCRIPTION
**Pull request by lustefaniak**
When message is sent to a new Shard which doesnt exists it is enqueued in MessageBufferMap. After Shard is added somewhere in the Cluster messages are replayed back using `MessageBuffer.foreach` and `tell`. At that point there is no Context available and Actor which receives the messages (even local one) doesn't have context available either.

### CODE REVIEW

**Comment by lustefaniak** [comment]
I think best approach to not introduce any allocation would be to store context using mixin in MessageBuffer.Node, but I couldn't make it work with my limited time and AspectJ knowledge.

I also couldn't find a way to access private fields of MessageBuffer and MessageBuffer.Node from the Aspect, If I could make it work I would rewrite whole `foreach` body with manually iterating over nodes and getting context from them.

**Review by lukasz-golebiewski — APPROVED** [review]

**Comment by ivantopo** [comment]
Hello @lustefaniak, thanks a lot for starting this :smile: 

> I think best approach to not introduce any allocation would be to store context using mixin in MessageBuffer.Node, but I couldn't make it work with my limited time and AspectJ knowledge.

I totally agree with doing it via mixins rather than wrapping the messages and just made a PR (see https://github.com/lustefaniak/kamon-akka-remote/pull/1) to your fork with that particular change, please take a look at it and if all is good please merge it and we can continue reviewing this PR. Fortunately there was a way of achieving context propagation without accessing private fields, usually when we have to do that there is no other way but to use reflection.

Looking forward to your comments!

**Comment by lustefaniak** [comment]
Wow, nice! I didn't notice they use apply on Node :-/

I tried to do something what your did with node, but context wasn't saved, I was missing this forced initialization.

What about akka 2.4? Do you want me to add support for it too?

**Comment by lustefaniak** [comment]
@ivantopo I simplified MessageBufferTest to only check saving and restoring Context in foreach and backported changes to Akka 2.4 too.

Is there anything else that should be done?

**Pull request merged**
